// C harness for the closure-return #interop tests. Each test prints
// one line tagged with a stable prefix; run.sh greps for the prefix
// and asserts the value.
//
// The closures themselves live in closures.tin. The header included
// below is generated by `tin build --emit-header=closures.h`.

#include "closures.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

int main(void) {
    /* 1. Single closure, single call. */
    tin_cb_i64_from_i64_t add5 = make_adder(5);
    if (!add5) { printf("FAIL_NULL_TRAMP\n"); return 1; }
    printf("add5(10)=%lld\n", (long long)add5(10));

    /* 2. Two adders live concurrently with different captures. */
    tin_cb_i64_from_i64_t add42 = make_adder(42);
    printf("add5(1)=%lld add42(1)=%lld add5(7)=%lld add42(8)=%lld\n",
        (long long)add5(1),
        (long long)add42(1),
        (long long)add5(7),
        (long long)add42(8));

    /* 3. Stateful closure: counter. Each invocation mutates captured cell. */
    tin_cb_i64_from_void_t ctr = make_counter();
    printf("ctr=%lld %lld %lld %lld\n",
        (long long)ctr(),
        (long long)ctr(),
        (long long)ctr(),
        (long long)ctr());

    /* 4. Independent counters do not share state. */
    tin_cb_i64_from_void_t ctr2 = make_counter();
    printf("ctr2=%lld ctr=%lld ctr2=%lld\n",
        (long long)ctr2(),
        (long long)ctr(),
        (long long)ctr2());

    /* 5. Free + re-allocate: the slot should be reusable. */
    tin_interop_closure_free(add5);
    tin_interop_closure_free(add42);

    tin_cb_i64_from_i64_t mul3 = make_multiplier(3);
    printf("mul3(7)=%lld\n", (long long)mul3(7));

    /* 6. Stress: 256 concurrent live trampolines (multi-page). */
    enum { N = 256 };
    tin_cb_i64_from_i64_t adders[N];
    for (int i = 0; i < N; i++) adders[i] = make_adder(i);
    long long sum = 0;
    for (int i = 0; i < N; i++) sum += adders[i](1000);
    printf("stress_sum=%lld\n", sum);
    for (int i = 0; i < N; i++) tin_interop_closure_free(adders[i]);

    /* 7. tin_interop_closure_free is NULL-safe. */
    tin_interop_closure_free(NULL);

    /* 8. Cleanup remaining live trampolines. */
    tin_interop_closure_free(ctr);
    tin_interop_closure_free(ctr2);
    tin_interop_closure_free(mul3);

    /* 9. String-returning closure: param + return marshaling. */
    tin_cb_string_from_string_t hi = make_greeter("hello");
    tin_cb_string_from_string_t bye = make_greeter("goodbye");
    const char *r1 = hi("ariel");
    const char *r2 = bye("ariel");
    const char *r3 = hi("world");
    printf("greet=%s|%s|%s\n", r1, r2, r3);
    free((void*)r1);
    free((void*)r2);
    free((void*)r3);
    tin_interop_closure_free(hi);
    tin_interop_closure_free(bye);

    /* 10. Bool-returning closure: i1 -> uint8_t marshaling. */
    tin_cb_bool_from_i64_t pred = make_predicate(10);
    printf("pred=%u %u %u\n",
        (unsigned)pred(5),
        (unsigned)pred(10),
        (unsigned)pred(11));
    tin_interop_closure_free(pred);

    /* 11. Reentrance: invoke trampoline A, whose argument value comes
       from invoking trampoline B. This exercises the path where the
       scratch register must be re-read at each dispatcher entry rather
       than cached across calls. */
    tin_cb_i64_from_i64_t outer = make_adder(1000);
    tin_cb_i64_from_i64_t inner = make_multiplier(2);
    printf("nested=%lld\n", (long long)outer(inner(7)));
    tin_interop_closure_free(outer);
    tin_interop_closure_free(inner);

    /* 12. String-PARAM marshaling leak stress: invoke a string-arg
       closure 10000 times. The dispatcher allocates a fresh ARC
       TinString via tin_interop_str_in for each call; without the
       post-call release path, RSS would grow ~64 bytes per call. */
    tin_cb_i64_from_string_t slen = make_strlen();
    long total = 0;
    for (int i = 0; i < 10000; i++) total += (long)slen("hello world");
    printf("string_stress=%ld\n", total);
    tin_interop_closure_free(slen);

    /* 13. Double-free is a no-op (don't crash, don't corrupt the
       free-list so subsequent allocs return distinct slots). */
    tin_cb_i64_from_i64_t df = make_adder(99);
    tin_interop_closure_free(df);
    tin_interop_closure_free(df);
    tin_cb_i64_from_i64_t b1 = make_adder(1);
    tin_cb_i64_from_i64_t b2 = make_adder(2);
    printf("double_free_distinct=%d slots=%lld %lld\n",
        (b1 != b2),
        (long long)b1(0),
        (long long)b2(0));
    tin_interop_closure_free(b1);
    tin_interop_closure_free(b2);

    /* 14. Bogus-pointer safety: a generic C cleanup routine routes
       everything through tin_interop_closure_free, including pointers
       that were never returned by us. None of these may SEGV.
         - libc fn pointer (printf)
         - small integer cast to pointer
         - stack pointer
         - middle of a string literal
         - pointer just past a real trampoline (off-by-some-bytes) */
    int stack_local = 0;
    char buf[32] = "not a trampoline";

    tin_cb_i64_from_i64_t real = make_adder(7);
    void *off_by_one = (char *)real + 1;

    tin_interop_closure_free((void *)printf);
    tin_interop_closure_free((void *)(uintptr_t)0x1234);
    tin_interop_closure_free(&stack_local);
    tin_interop_closure_free(buf);
    tin_interop_closure_free(off_by_one);

    /* The real trampoline must still be invocable + freeable - the
       bogus calls above must not have corrupted any state. */
    long long after = (long long)real(100);
    tin_interop_closure_free(real);
    printf("bogus_safe after=%lld\n", after);

    /* 15. Leaked trampolines: deliberately do NOT free these. The
       atexit handler must release their captured envs and munmap the
       page so leak detectors stay quiet. (Verified by run.sh under
       valgrind when --valgrind is passed.) */
    for (int i = 0; i < 5; i++) {
        tin_cb_i64_from_i64_t leaked = make_adder(i);
        leaked(0);  /* use it once so the optimizer can't elide the call */
    }
    printf("leaked=5\n");

    printf("done\n");
    return 0;
}
