package codegen

// `#interop` C header generation.
//
// `tin build --emit-header=<path>` produces a single `.h` file
// declaring every #interop function in the program along with the
// boilerplate needed to use them: the `tin_set_extern_alloc` setter
// declaration. Type mapping mirrors what emitInteropWrapperFor emits
// at the IR level - keep these two in sync.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Azer0s/tin/ast"
)

// writeInteropHeader emits a C header file at cg.emitHeaderPath.
// One prototype per #interop function plus a small fixed preamble.
func (cg *CodeGen) writeInteropHeader(stmts []ast.Node) error {
	var b strings.Builder

	guard := headerGuardName(cg.emitHeaderPath)

	b.WriteString("/* Auto-generated by tin --emit-header. Do not edit. */\n")
	b.WriteString("#ifndef " + guard + "\n")
	b.WriteString("#define " + guard + "\n\n")
	b.WriteString("#include <stdint.h>\n")
	b.WriteString("#include <stddef.h>\n\n")
	b.WriteString("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")

	// Allocator-callback + runtime-init declarations. Always emitted so
	// the typedefs are available even when no #interop function uses
	// them directly.
	b.WriteString("/* Optional: explicitly bring up the runtime before any #interop call.\n")
	b.WriteString("   Idempotent; the wrapper preamble calls it on every entry. */\n")
	b.WriteString("void tin_runtime_init(void);\n\n")
	b.WriteString("/* Allocator hook used when #interop returns string / [T]. */\n")
	b.WriteString("typedef void *(*tin_alloc_fn)(size_t);\n")
	b.WriteString("void tin_set_extern_alloc(tin_alloc_fn fn);\n\n")

	for _, node := range stmts {
		fn, ok := node.(*ast.FuncDecl)
		if !ok || !hasTag(fn.Tags, "interop") {
			continue
		}

		writeInteropPrototype(&b, fn)
	}

	b.WriteString("\n#ifdef __cplusplus\n}\n#endif\n")
	b.WriteString("#endif /* " + guard + " */\n")

	if err := os.WriteFile(cg.emitHeaderPath, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("--emit-header: %w", err)
	}

	return nil
}

// writeInteropPrototype renders one C prototype + an inline comment
// echoing the original Tin signature.
func writeInteropPrototype(b *strings.Builder, fn *ast.FuncDecl) {
	retC := cReturnType(fn.RetType)
	cParams, sliceReturnExtras := cParamList(fn)

	allParams := cParams
	allParams = append(allParams, sliceReturnExtras...)

	if len(allParams) == 0 {
		allParams = []string{"void"}
	}

	fmt.Fprintf(b, "/* Tin: %s */\n", tinSignatureString(fn))
	fmt.Fprintf(b, "%s %s(%s);\n\n", retC, fn.Name, strings.Join(allParams, ", "))
}

// cReturnType maps the Tin return type to its C wrapper return.
// Slice returns become `int` (the status return). String returns
// become `const char*`. Everything else uses cTypeName.
func cReturnType(t ast.TypeExpr) string {
	if t == nil {
		return "void"
	}

	if at, ok := t.(*ast.ArrayType); ok && at.Size < 0 {
		return "int"
	}

	if st, ok := t.(*ast.SimpleType); ok && st.Name == "string" {
		return "const char *"
	}

	return cTypeName(t)
}

// cParamList builds the C parameter list and any extra trailing
// out-params required by a slice return (matches the wrapper IR
// signature).
func cParamList(fn *ast.FuncDecl) ([]string, []string) {
	out := make([]string, 0, len(fn.Params))

	for _, p := range fn.Params {
		if at, ok := p.Type.(*ast.ArrayType); ok && at.Size < 0 {
			elem := cTypeName(at.Elem)
			out = append(out,
				fmt.Sprintf("const %s *%s", elem, p.Name),
				fmt.Sprintf("int64_t %s_len", p.Name))

			continue
		}

		if st, ok := p.Type.(*ast.SimpleType); ok && st.Name == "string" {
			out = append(out, fmt.Sprintf("const char *%s", p.Name))
			continue
		}

		if ft, ok := p.Type.(*ast.FuncType); ok {
			out = append(out, cCallbackDecl(ft, p.Name))
			continue
		}

		out = append(out, fmt.Sprintf("%s %s", cTypeName(p.Type), p.Name))
	}

	var extras []string

	if at, ok := fn.RetType.(*ast.ArrayType); ok && at.Size < 0 {
		elem := cTypeName(at.Elem)
		extras = append(extras,
			fmt.Sprintf("%s **out_data", elem),
			"int64_t *out_len")
	}

	return out, extras
}

// cCallbackDecl renders a callback parameter declaration in C
// function-pointer syntax: `R (*name)(A1, A2, ...)`.
func cCallbackDecl(ft *ast.FuncType, name string) string {
	ret := "void"
	if ft.RetType != nil {
		ret = cTypeName(ft.RetType)
	}

	parts := make([]string, 0, len(ft.Params))
	for _, p := range ft.Params {
		parts = append(parts, cTypeName(p))
	}

	if len(parts) == 0 {
		parts = []string{"void"}
	}

	return fmt.Sprintf("%s (*%s)(%s)", ret, name, strings.Join(parts, ", "))
}

// cTypeName maps Tin scalar / pointer types to their C-equivalent
// declaration spelling. Anything outside the interop whitelist
// renders as `void *` (single pointer) so the emitted header stays
// self-contained - users can cast on the C side.
func cTypeName(t ast.TypeExpr) string {
	if name, ok := primitiveCName(t); ok {
		return name
	}

	if pt, ok := t.(*ast.PointerType); ok {
		if name, ok := primitiveCName(pt.Elem); ok {
			return name + " *"
		}

		// Pointer to anything we can't render in pure C (user struct,
		// trait, ADT, generic). Collapse to a single opaque void *
		// rather than emit "Foo *" for an undefined Foo.
		return "void *"
	}

	return "void *"
}

// primitiveCName returns the C spelling for a Tin SimpleType when the
// name maps to a stable C primitive, plus an ok flag.
func primitiveCName(t ast.TypeExpr) (string, bool) {
	st, ok := t.(*ast.SimpleType)
	if !ok {
		return "", false
	}

	switch st.Name {
	case "i8":
		return "int8_t", true
	case "i16":
		return "int16_t", true
	case "i32":
		return "int32_t", true
	case "i64":
		return "int64_t", true
	case "u8":
		return "uint8_t", true
	case "u16":
		return "uint16_t", true
	case "u32", "uint32":
		return "uint32_t", true
	case "u64", "size_t":
		return "uint64_t", true
	case "f32":
		return "float", true
	case "f64":
		return "double", true
	case "bool":
		return "uint8_t", true
	case "char", "byte":
		return "char", true
	case "void":
		return "void", true
	}

	return "", false
}

// tinSignatureString renders the Tin signature back into the comment
// header so users can correlate the C declaration with the original.
func tinSignatureString(fn *ast.FuncDecl) string {
	var sb strings.Builder

	sb.WriteString("fn{#interop} ")
	sb.WriteString(fn.Name)
	sb.WriteString("(")

	for i, p := range fn.Params {
		if i > 0 {
			sb.WriteString(", ")
		}

		sb.WriteString(p.Name)
		sb.WriteString(" ")
		sb.WriteString(p.Type.String())
	}

	sb.WriteString(")")

	if fn.RetType != nil {
		sb.WriteString(" ")
		sb.WriteString(fn.RetType.String())
	}

	return sb.String()
}

// headerGuardName derives a C include-guard from the output path -
// uppercase, alphanumerics + underscores, with the file extension
// stripped. e.g. `out/foo.h` -> `OUT_FOO_H`.
func headerGuardName(path string) string {
	base := filepath.Base(path)
	base = strings.TrimSuffix(base, filepath.Ext(base))

	var sb strings.Builder

	for _, r := range strings.ToUpper(base) {
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			sb.WriteRune(r)
		} else {
			sb.WriteRune('_')
		}
	}

	sb.WriteString("_H")

	return sb.String()
}
