package codegen

// `#interop` C header generation.
//
// `tin build --emit-header=<path>` produces a single `.h` file
// declaring every #interop function in the program along with the
// boilerplate needed to use them: the `tin_set_extern_alloc` setter
// declaration. Type mapping mirrors what emitInteropWrapperFor emits
// at the IR level - keep these two in sync.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Azer0s/tin/ast"
)

// writeInteropHeader emits a C header file at cg.emitHeaderPath.
// One prototype per #interop function plus a small fixed preamble.
func (cg *CodeGen) writeInteropHeader(stmts []ast.Node) error {
	var b strings.Builder

	guard := headerGuardName(cg.emitHeaderPath)

	b.WriteString("/* Auto-generated by tin --emit-header. Do not edit. */\n")
	b.WriteString("#ifndef " + guard + "\n")
	b.WriteString("#define " + guard + "\n\n")
	b.WriteString("#include <stdint.h>\n")
	b.WriteString("#include <stddef.h>\n\n")
	b.WriteString("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")

	// Emit C struct typedefs for every #packed struct that appears in
	// any #interop signature (param or return). Users get a layout
	// matching the wrapper's expected one without hand-writing it.
	cg.writePackedStructTypedefs(&b, stmts)

	// Allocator-callback + runtime-init declarations. Always emitted so
	// the typedefs are available even when no #interop function uses
	// them directly.
	b.WriteString("/* Optional: explicitly bring up the runtime before any #interop call.\n")
	b.WriteString("   Idempotent; the wrapper preamble calls it on every entry. */\n")
	b.WriteString("void tin_runtime_init(void);\n\n")
	b.WriteString("/* Drop one ARC reference to a Tin-allocated block returned through\n")
	b.WriteString("   a #interop *void handle. NULL-safe. */\n")
	b.WriteString("void tin_release(void *ptr);\n\n")
	b.WriteString("/* Allocator hook used when #interop returns string / [T]. */\n")
	b.WriteString("typedef void *(*tin_alloc_fn)(size_t);\n")
	b.WriteString("void tin_set_extern_alloc(tin_alloc_fn fn);\n\n")

	// fn-pointer-returning #interop functions hand back a per-instance
	// trampoline. The user calls tin_interop_closure_free on it when
	// done so the slot and its captured env are released. NULL-safe.
	if anyCallbackReturn(stmts) {
		b.WriteString("/* Release a function pointer returned by an #interop callback-returning\n")
		b.WriteString("   function. Frees the trampoline slot and drops the captured env's\n")
		b.WriteString("   ARC reference. NULL-safe; ignores pointers that are not Tin\n")
		b.WriteString("   trampolines. */\n")
		b.WriteString("void tin_interop_closure_free(void *tramp);\n\n")
	}

	// Pre-emit one typedef per unique callback-return signature so the
	// prototypes can spell the return type as `tin_cb_<sig>_t` instead
	// of the unreadable inline `R (*name(args))(cb_args)` form.
	cbTypedefs := cg.collectCallbackReturnTypedefs(stmts)
	if len(cbTypedefs) > 0 {
		b.WriteString("/* Function-pointer typedefs for #interop callback returns. */\n")

		for _, td := range cbTypedefs {
			b.WriteString(td.line + "\n")
		}

		b.WriteString("\n")
	}

	for _, node := range stmts {
		fn, ok := node.(*ast.FuncDecl)
		if !ok || !hasTag(fn.Tags, "interop") {
			continue
		}

		cg.writeInteropPrototype(&b, fn)
	}

	b.WriteString("\n#ifdef __cplusplus\n}\n#endif\n")
	b.WriteString("#endif /* " + guard + " */\n")

	if err := os.WriteFile(cg.emitHeaderPath, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("--emit-header: %w", err)
	}

	return nil
}

// writeInteropPrototype renders one C prototype + an inline comment
// echoing the original Tin signature.
func (cg *CodeGen) writeInteropPrototype(b *strings.Builder, fn *ast.FuncDecl) {
	retC := cg.cReturnType(fn.RetType)
	cParams, sliceReturnExtras := cg.cParamList(fn)

	allParams := cParams
	allParams = append(allParams, sliceReturnExtras...)

	if len(allParams) == 0 {
		allParams = []string{"void"}
	}

	fmt.Fprintf(b, "/* Tin: %s */\n", tinSignatureString(fn))
	fmt.Fprintf(b, "%s %s(%s);\n\n", retC, fn.Name, strings.Join(allParams, ", "))
}

// cReturnType maps the Tin return type to its C wrapper return.
// Slice returns become `int` (the status return). String returns
// become `const char*`. Packed structs use the typedef'd struct name.
// Function-pointer returns use the per-signature `tin_cb_<sig>_t`
// typedef pre-emitted at the top of the header. Everything else uses
// cTypeName.
func (cg *CodeGen) cReturnType(t ast.TypeExpr) string {
	if t == nil {
		return "void"
	}

	if at, ok := t.(*ast.ArrayType); ok && at.Size < 0 {
		return "int"
	}

	if st, ok := t.(*ast.SimpleType); ok {
		if st.Name == "string" {
			return "const char *"
		}

		if cg.interopPackedStructs[st.Name] {
			return st.Name
		}
	}

	if ft, ok := t.(*ast.FuncType); ok {
		return callbackReturnTypedefName(ft)
	}

	return cTypeName(t)
}

// cParamList builds the C parameter list and any extra trailing
// out-params required by a slice return (matches the wrapper IR
// signature).
func (cg *CodeGen) cParamList(fn *ast.FuncDecl) ([]string, []string) {
	out := make([]string, 0, len(fn.Params))

	for _, p := range fn.Params {
		if at, ok := p.Type.(*ast.ArrayType); ok && at.Size < 0 {
			elem := cTypeName(at.Elem)
			out = append(out,
				fmt.Sprintf("const %s *%s", elem, p.Name),
				fmt.Sprintf("int64_t %s_len", p.Name))

			continue
		}

		if st, ok := p.Type.(*ast.SimpleType); ok && st.Name == "string" {
			out = append(out, fmt.Sprintf("const char *%s", p.Name))

			continue
		}

		if st, ok := p.Type.(*ast.SimpleType); ok && cg.interopPackedStructs[st.Name] {
			out = append(out, fmt.Sprintf("%s %s", st.Name, p.Name))

			continue
		}

		if ft, ok := p.Type.(*ast.FuncType); ok {
			out = append(out, cCallbackDecl(ft, p.Name))

			continue
		}

		out = append(out, fmt.Sprintf("%s %s", cTypeName(p.Type), p.Name))
	}

	var extras []string

	if at, ok := fn.RetType.(*ast.ArrayType); ok && at.Size < 0 {
		elem := cTypeName(at.Elem)
		extras = append(extras,
			fmt.Sprintf("%s **out_data", elem),
			"int64_t *out_len")
	}

	return out, extras
}

// writePackedStructTypedefs scans all #interop signatures, finds the
// #packed user struct names referenced by value, and emits a C
// `typedef struct __attribute__((packed)) { ... } Name;` for each so
// the user's C code can declare and pass values directly.
func (cg *CodeGen) writePackedStructTypedefs(b *strings.Builder, stmts []ast.Node) {
	used := map[string]bool{}

	addIfPacked := func(t ast.TypeExpr) {
		if t == nil {
			return
		}

		st, ok := t.(*ast.SimpleType)
		if !ok || !cg.interopPackedStructs[st.Name] {
			return
		}

		used[st.Name] = true
	}

	for _, node := range stmts {
		fn, ok := node.(*ast.FuncDecl)
		if !ok || !hasTag(fn.Tags, "interop") {
			continue
		}

		for _, p := range fn.Params {
			addIfPacked(p.Type)
		}

		addIfPacked(fn.RetType)
	}

	if len(used) == 0 {
		return
	}

	b.WriteString("/* #packed Tin structs surfaced at the interop boundary. */\n")

	for _, node := range stmts {
		sd, ok := node.(*ast.StructDecl)
		if !ok || !used[sd.Name] {
			continue
		}

		b.WriteString("typedef struct __attribute__((packed)) {\n")

		for _, f := range sd.Fields {
			b.WriteString("    " + cTypeName(f.Type) + " " + f.Name + ";\n")
		}

		b.WriteString("} " + sd.Name + ";\n\n")
	}
}

// cCallbackDecl renders a callback parameter declaration in C
// function-pointer syntax: `R (*name)(A1, A2, ...)`.
func cCallbackDecl(ft *ast.FuncType, name string) string {
	ret := "void"
	if ft.RetType != nil {
		ret = cTypeName(ft.RetType)
	}

	parts := make([]string, 0, len(ft.Params))
	for _, p := range ft.Params {
		parts = append(parts, cTypeName(p))
	}

	if len(parts) == 0 {
		parts = []string{"void"}
	}

	return fmt.Sprintf("%s (*%s)(%s)", ret, name, strings.Join(parts, ", "))
}

type callbackTypedef struct {
	name string
	line string
}

// anyCallbackReturn reports whether any #interop function in the
// program returns a function pointer.
func anyCallbackReturn(stmts []ast.Node) bool {
	for _, node := range stmts {
		fn, ok := node.(*ast.FuncDecl)
		if !ok || !hasTag(fn.Tags, "interop") {
			continue
		}

		if _, ok := fn.RetType.(*ast.FuncType); ok {
			return true
		}
	}

	return false
}

// collectCallbackReturnTypedefs walks all #interop functions and
// returns one C typedef per unique callback-return signature. Each
// typedef has the form `typedef R (*tin_cb_<sig>_t)(A1, A2, ...);` so
// the wrapper prototype can use `tin_cb_<sig>_t` as a clean return
// type instead of the inline function-pointer syntax.
func (cg *CodeGen) collectCallbackReturnTypedefs(stmts []ast.Node) []callbackTypedef {
	seen := map[string]bool{}
	out := []callbackTypedef{}

	for _, node := range stmts {
		fn, ok := node.(*ast.FuncDecl)
		if !ok || !hasTag(fn.Tags, "interop") {
			continue
		}

		ft, ok := fn.RetType.(*ast.FuncType)
		if !ok {
			continue
		}

		name := callbackReturnTypedefName(ft)
		if seen[name] {
			continue
		}

		seen[name] = true

		// Match the dispatcher's C-side signature: bool widens to
		// uint8_t, string returns/params become const char*, slice
		// params split into (T *data, int64_t len). String returns
		// from the closure are emitted as `const char *` so the user
		// can read the bytes without casting.
		ret := "void"
		if ft.RetType != nil {
			ret = cReturnSpellingForCallback(ft.RetType)
		}

		parts := make([]string, 0, len(ft.Params))
		for _, p := range ft.Params {
			parts = append(parts, cParamSpellingForCallback(p)...)
		}

		if len(parts) == 0 {
			parts = []string{"void"}
		}

		out = append(out, callbackTypedef{
			name: name,
			line: fmt.Sprintf("typedef %s (*%s)(%s);", ret, name, strings.Join(parts, ", ")),
		})
	}

	return out
}

// cParamSpellingForCallback maps a Tin callback param type to the
// 1-or-2 C type spellings the dispatcher will receive. Mirrors
// cParamExpansion (codegen) so the typedef and the dispatcher signature
// stay byte-compatible.
func cParamSpellingForCallback(t ast.TypeExpr) []string {
	if st, ok := t.(*ast.SimpleType); ok {
		switch st.Name {
		case "string":
			return []string{"const char *"}
		case "bool":
			return []string{"uint8_t"}
		}
	}

	if at, ok := t.(*ast.ArrayType); ok && at.Size < 0 {
		return []string{cTypeName(at.Elem) + " *", "int64_t"}
	}

	return []string{cTypeName(t)}
}

// cReturnSpellingForCallback maps a Tin callback return type to the
// C type spelling the dispatcher returns. Mirrors cReturnLLVM.
func cReturnSpellingForCallback(t ast.TypeExpr) string {
	if st, ok := t.(*ast.SimpleType); ok {
		switch st.Name {
		case "string":
			return "const char *"
		case "bool":
			return "uint8_t"
		}
	}

	return cTypeName(t)
}

// callbackReturnTypedefName builds a stable, readable typedef name
// from a Tin callback signature using Tin type spellings (i64, string,
// bool, ...) joined by `_from_`. A function returning the type pointer
// reads naturally:
//
//	fn() i64                    -> tin_cb_i64_from_void_t
//	fn(i64) i64                 -> tin_cb_i64_from_i64_t
//	fn(i64, i64) i64            -> tin_cb_i64_from_i64_i64_t
//	fn(string) string           -> tin_cb_string_from_string_t
//	fn(i64) bool                -> tin_cb_bool_from_i64_t
//	fn([i64]) i64               -> tin_cb_i64_from_slice_i64_t
//	fn(*i64) void               -> tin_cb_void_from_i64ptr_t
//
// Names are derived from the Tin AST so they stay aligned with what
// the user wrote, not the C ABI shape. The typedef body still spells
// out the C ABI types via cParamSpellingForCallback / cReturnSpellingForCallback.
func callbackReturnTypedefName(ft *ast.FuncType) string {
	var sb strings.Builder

	sb.WriteString("tin_cb_")

	if ft.RetType == nil {
		sb.WriteString("void")
	} else {
		sb.WriteString(tinTypeNameToken(ft.RetType))
	}

	sb.WriteString("_from_")

	if len(ft.Params) == 0 {
		sb.WriteString("void")
	} else {
		for i, p := range ft.Params {
			if i > 0 {
				sb.WriteString("_")
			}

			sb.WriteString(tinTypeNameToken(p))
		}
	}

	sb.WriteString("_t")

	return sb.String()
}

// tinTypeNameToken returns a single C-identifier token that names the
// given Tin type using Tin's own spelling. Used when constructing the
// readable callback typedef names.
//
//	i32, i64, u8, f64, bool, string, void, char, byte -> as-is
//	*T   -> "<T>ptr" recursively (e.g. *i64 -> "i64ptr", *void -> "voidptr")
//	[T]  -> "slice_<T>" (e.g. [i64] -> "slice_i64")
//	other -> "opaque" (the typedef body already widens to `void *`)
func tinTypeNameToken(t ast.TypeExpr) string {
	if t == nil {
		return "void"
	}

	if st, ok := t.(*ast.SimpleType); ok {
		// Tin's own primitive spellings are already valid C identifiers,
		// so we can pass them through directly. Anything else falls
		// back to "opaque".
		switch st.Name {
		case "i8", "i16", "i32", "i64",
			"u8", "u16", "u32", "u64",
			"f32", "f64",
			"bool", "string", "void",
			"char", "byte",
			"int", "uint", "size_t":
			return st.Name
		}

		return "opaque"
	}

	if pt, ok := t.(*ast.PointerType); ok {
		return tinTypeNameToken(pt.Elem) + "ptr"
	}

	if at, ok := t.(*ast.ArrayType); ok && at.Size < 0 {
		return "slice_" + tinTypeNameToken(at.Elem)
	}

	return "opaque"
}

// cTypeName maps Tin scalar / pointer types to their C-equivalent
// declaration spelling. Anything outside the interop whitelist
// renders as `void *` (single pointer) so the emitted header stays
// self-contained - users can cast on the C side.
func cTypeName(t ast.TypeExpr) string {
	if name, ok := primitiveCName(t); ok {
		return name
	}

	if pt, ok := t.(*ast.PointerType); ok {
		if name, ok := primitiveCName(pt.Elem); ok {
			return name + " *"
		}

		// Pointer to anything we can't render in pure C (user struct,
		// trait, ADT, generic). Collapse to a single opaque void *
		// rather than emit "Foo *" for an undefined Foo.
		return "void *"
	}

	return "void *"
}

// primitiveCName returns the C spelling for a Tin SimpleType when the
// name maps to a stable C primitive, plus an ok flag.
func primitiveCName(t ast.TypeExpr) (string, bool) {
	st, ok := t.(*ast.SimpleType)
	if !ok {
		return "", false
	}

	switch st.Name {
	case "i8":
		return "int8_t", true
	case "i16":
		return "int16_t", true
	case "i32":
		return "int32_t", true
	case "i64":
		return "int64_t", true
	case "u8":
		return "uint8_t", true
	case "u16":
		return "uint16_t", true
	case "u32", "uint32":
		return "uint32_t", true
	case "u64", "size_t":
		return "uint64_t", true
	case "f32":
		return "float", true
	case "f64":
		return "double", true
	case "bool":
		return "uint8_t", true
	case "char", "byte":
		return "char", true
	case "void":
		return "void", true
	}

	return "", false
}

// tinSignatureString renders the Tin signature back into the comment
// header so users can correlate the C declaration with the original.
func tinSignatureString(fn *ast.FuncDecl) string {
	var sb strings.Builder

	sb.WriteString("fn{#interop} ")
	sb.WriteString(fn.Name)
	sb.WriteString("(")

	for i, p := range fn.Params {
		if i > 0 {
			sb.WriteString(", ")
		}

		sb.WriteString(p.Name)
		sb.WriteString(" ")
		sb.WriteString(p.Type.String())
	}

	sb.WriteString(")")

	if fn.RetType != nil {
		sb.WriteString(" ")
		sb.WriteString(fn.RetType.String())
	}

	return sb.String()
}

// headerGuardName derives a C include-guard from the output path -
// uppercase, alphanumerics + underscores, with the file extension
// stripped. e.g. `out/foo.h` -> `OUT_FOO_H`.
func headerGuardName(path string) string {
	base := filepath.Base(path)
	base = strings.TrimSuffix(base, filepath.Ext(base))

	var sb strings.Builder

	for _, r := range strings.ToUpper(base) {
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			sb.WriteRune(r)
		} else {
			sb.WriteRune('_')
		}
	}

	sb.WriteString("_H")

	return sb.String()
}
